export enum Character {
  NoAnswer = 1,
  Other = 2,
  Hiccup = 3,
  Toothless = 4,
  Astrid = 5,
  Stoick = 6,
  Valka = 7,
  Gobber = 8,
  Ruffnut = 9,
  Tuffnut = 10,
  Twins = 11,
  Snotlout = 12,
  Fishlegs = 13,
  Cloudjumper = 14,
  Drago = 15,
  Eret = 16,
  Thotfury = 17,
  Grimmel = 18,
}
