export enum Platform {
  None = 0,
  Reddit = 1,
  Discord = 2,
  Instagram = 3,
  Tumblr = 4,
  FandomWiki = 5,
  Facebook = 6,
  Grapevine = 7,
  Amino = 8,
  Youtube = 9,
  PlatformShy = 10,
  Multiple = 11,
  Other = 12,
}
